services:
  club_app: &app
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-dev
    container_name: club_app
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - PYTHONWARNINGS=ignore
      - POSTGRES_DB=nes_club
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    volumes:
      - ${PWD}:/app:delegated # enable hot code reload in debug mode
    depends_on:
      - postgres
      - redis
      - queue
      - webpack
    ports:
      - "8000:8000"

  queue:
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-queue
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - PYTHONWARNINGS=ignore
      - POSTGRES_DB=nes_club
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    volumes:
      - ${PWD}:/app:delegated
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14
    container_name: club_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nes_club

  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  webpack:
    image: node:14-slim
    command: npm run watch
    restart: always
    environment:
      - BROWSERSLIST_IGNORE_OLD_DATA=1
    volumes:
      - ${PWD}:/app:delegated
    working_dir: /app/frontend

  bot:
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-bot
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - PYTHONWARNINGS=ignore
      - POSTGRES_DB=nes_club
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    volumes:
      - ${PWD}:/app:delegated
    depends_on:
      - club_app
      - postgres
      - redis

  helpdeskbot:
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-helpdeskbot
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - PYTHONWARNINGS=ignore
      - POSTGRES_DB=nes_club
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    volumes:
      - ${PWD}:/app:delegated
    depends_on:
      - club_app
      - postgres
      - redis
